#!/bin/sh
#
# falcon-gateway   init file for starting up the falcon-gateway
#
# chkconfig:   - 87 13
# description: Starts and stops the falcon-gateway daemon.
# config: /etc/falcon/gateway/cfg.json
# pidfile:
#
### BEGIN INIT INFO
# Provides: falcon-gateway
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop falcon-gateway
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

name="falcon-gateway"
exec="/usr/local/bin/$name"
falcon_user=falcon
confile="/etc/falcon/gateway/cfg.json"
logfile="/var/log/falcon/gateway/gateway.log"
pidfile="/var/run/falcon/gateway.pid"
lockfile="/var/lock/subsys/falcon-gateway"


start() {
    [ -f $confile ] || exit 6
    [ -x $exec ] || exit 5
    echo -n $"Starting $name: "
    daemon --user ${falcon_user} --pidfile=${pidfile} "$exec -c $confile >> $logfile 2>&1 &"
    retval=$?
    echo
    [ $retval -eq 0 ] && (touch $lockfile; pidof $name > $pidfile)

    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    killproc -p $pidfile $name
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $pidfile $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    false
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
exit $?
